### PR TITLE
Gcc as $CC

### PR DESCRIPTION
**Pull request by RohanVashisht1234**

### CODE REVIEW

**Comment by adamharrison** [comment]
The reason this is like this currently, is that we require Lua to be compiled for the host, not the target. If we change to CC from GCC here, cross-compiles won't work. 

This should probably be changed to a secondary variable HOSTCC.

**Comment by RohanVashisht1234** [comment]
Nice idea,I am changing this.

**Comment by RohanVashisht1234** [comment]
Ok Adam, changes have been done to the build.sh file.

**Comment by adamharrison** [comment]
Set it so it's equal to CC by default, and then we're good

**Comment by RohanVashisht1234** [comment]
I think I have fixed it now

**Pull request merged**
